import { SWMMState } from './swmm-types';

export interface DemoModel {
  id: string;
  name: string;
  description: string;
  emoji: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  nodeCount: number;
  linkCount: number;
  model: SWMMState;
}

export const DEMO_MODELS: DemoModel[] = [
  {
    id: 'simple-linear',
    name: 'Simple Pipe Run',
    description: 'Three junctions in a row draining to one outfall. The simplest possible network.',
    emoji: '🔰',
    difficulty: 'Beginner',
    nodeCount: 4,
    linkCount: 3,
    model: {
      nodes: [
        { id: 'J1', type: 'junction', x: 200, y: 300, invertElev: 110, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J2', type: 'junction', x: 380, y: 300, invertElev: 105, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J3', type: 'junction', x: 560, y: 300, invertElev: 100, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'O1', type: 'outfall', x: 740, y: 300, invertElev: 95, maxDepth: 0, depth: 0, isSurcharged: false },
      ],
      links: [
        { id: 'C1', type: 'conduit', fromNode: 'J1', toNode: 'J2', length: 180, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C2', type: 'conduit', fromNode: 'J2', toNode: 'J3', length: 180, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C3', type: 'conduit', fromNode: 'J3', toNode: 'O1', length: 180, roughness: 0.013, flow: 0, capacity: 10 },
      ],
      subcatchments: [],
    },
  },
  {
    id: 'y-branch',
    name: 'Y-Branch Network',
    description: 'Two upstream branches merge at a junction before draining to the outfall. Tests merging flows.',
    emoji: '🔀',
    difficulty: 'Beginner',
    nodeCount: 6,
    linkCount: 5,
    model: {
      nodes: [
        { id: 'J1', type: 'junction', x: 150, y: 180, invertElev: 115, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J2', type: 'junction', x: 150, y: 420, invertElev: 115, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J3', type: 'junction', x: 350, y: 180, invertElev: 110, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J4', type: 'junction', x: 350, y: 420, invertElev: 110, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J5', type: 'junction', x: 550, y: 300, invertElev: 100, maxDepth: 12, depth: 0, isSurcharged: false },
        { id: 'O1', type: 'outfall', x: 750, y: 300, invertElev: 95, maxDepth: 0, depth: 0, isSurcharged: false },
      ],
      links: [
        { id: 'C1', type: 'conduit', fromNode: 'J1', toNode: 'J3', length: 200, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C2', type: 'conduit', fromNode: 'J2', toNode: 'J4', length: 200, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C3', type: 'conduit', fromNode: 'J3', toNode: 'J5', length: 230, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C4', type: 'conduit', fromNode: 'J4', toNode: 'J5', length: 230, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C5', type: 'conduit', fromNode: 'J5', toNode: 'O1', length: 200, roughness: 0.013, flow: 0, capacity: 15 },
      ],
      subcatchments: [],
    },
  },
  {
    id: 'storage-basin',
    name: 'Storage Basin Design',
    description: 'A network with a detention pond that absorbs peak flows before releasing downstream. Watch how storage delays the flood peak.',
    emoji: '🏊',
    difficulty: 'Intermediate',
    nodeCount: 7,
    linkCount: 6,
    model: {
      nodes: [
        { id: 'J1', type: 'junction', x: 150, y: 200, invertElev: 120, maxDepth: 8, depth: 0, isSurcharged: false },
        { id: 'J2', type: 'junction', x: 150, y: 400, invertElev: 118, maxDepth: 8, depth: 0, isSurcharged: false },
        { id: 'J3', type: 'junction', x: 350, y: 300, invertElev: 112, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'S1', type: 'storage', x: 520, y: 200, invertElev: 105, maxDepth: 15, depth: 0, isSurcharged: false },
        { id: 'J4', type: 'junction', x: 520, y: 400, invertElev: 108, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J5', type: 'junction', x: 700, y: 300, invertElev: 100, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'O1', type: 'outfall', x: 870, y: 300, invertElev: 95, maxDepth: 0, depth: 0, isSurcharged: false },
      ],
      links: [
        { id: 'C1', type: 'conduit', fromNode: 'J1', toNode: 'J3', length: 220, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C2', type: 'conduit', fromNode: 'J2', toNode: 'J3', length: 220, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C3', type: 'conduit', fromNode: 'J3', toNode: 'S1', length: 200, roughness: 0.013, flow: 0, capacity: 12 },
        { id: 'C4', type: 'conduit', fromNode: 'J3', toNode: 'J4', length: 200, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C5', type: 'conduit', fromNode: 'S1', toNode: 'J5', length: 200, roughness: 0.013, flow: 0, capacity: 6 },
        { id: 'C6', type: 'conduit', fromNode: 'J5', toNode: 'O1', length: 170, roughness: 0.013, flow: 0, capacity: 15 },
      ],
      subcatchments: [],
    },
  },
  {
    id: 'grid-network',
    name: 'City Block Grid',
    description: 'A 3x2 grid of junctions simulating a small city block drainage system. Multiple flow paths prevent bottlenecks.',
    emoji: '🏙️',
    difficulty: 'Intermediate',
    nodeCount: 8,
    linkCount: 9,
    model: {
      nodes: [
        { id: 'J1', type: 'junction', x: 150, y: 180, invertElev: 115, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J2', type: 'junction', x: 350, y: 180, invertElev: 112, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J3', type: 'junction', x: 550, y: 180, invertElev: 108, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J4', type: 'junction', x: 150, y: 400, invertElev: 113, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J5', type: 'junction', x: 350, y: 400, invertElev: 110, maxDepth: 12, depth: 0, isSurcharged: false },
        { id: 'J6', type: 'junction', x: 550, y: 400, invertElev: 105, maxDepth: 12, depth: 0, isSurcharged: false },
        { id: 'J7', type: 'junction', x: 750, y: 300, invertElev: 100, maxDepth: 14, depth: 0, isSurcharged: false },
        { id: 'O1', type: 'outfall', x: 900, y: 300, invertElev: 95, maxDepth: 0, depth: 0, isSurcharged: false },
      ],
      links: [
        { id: 'C1', type: 'conduit', fromNode: 'J1', toNode: 'J2', length: 200, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C2', type: 'conduit', fromNode: 'J2', toNode: 'J3', length: 200, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C3', type: 'conduit', fromNode: 'J4', toNode: 'J5', length: 200, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C4', type: 'conduit', fromNode: 'J5', toNode: 'J6', length: 200, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C5', type: 'conduit', fromNode: 'J1', toNode: 'J4', length: 220, roughness: 0.013, flow: 0, capacity: 6 },
        { id: 'C6', type: 'conduit', fromNode: 'J2', toNode: 'J5', length: 220, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C7', type: 'conduit', fromNode: 'J3', toNode: 'J6', length: 220, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C8', type: 'conduit', fromNode: 'J3', toNode: 'J7', length: 230, roughness: 0.013, flow: 0, capacity: 12 },
        { id: 'C9', type: 'conduit', fromNode: 'J6', toNode: 'J7', length: 230, roughness: 0.013, flow: 0, capacity: 12 },
      ],
      subcatchments: [],
    },
  },
  {
    id: 'flood-prone',
    name: 'Undersized Flood Zone',
    description: 'A deliberately undersized network that WILL flood during simulation. Watch Steve panic as nodes surcharge! Can you fix it?',
    emoji: '🌊',
    difficulty: 'Intermediate',
    nodeCount: 5,
    linkCount: 4,
    model: {
      nodes: [
        { id: 'J1', type: 'junction', x: 180, y: 200, invertElev: 110, maxDepth: 4, depth: 0, isSurcharged: false },
        { id: 'J2', type: 'junction', x: 380, y: 250, invertElev: 108, maxDepth: 3, depth: 0, isSurcharged: false },
        { id: 'J3', type: 'junction', x: 580, y: 300, invertElev: 105, maxDepth: 3, depth: 0, isSurcharged: false },
        { id: 'J4', type: 'junction', x: 180, y: 400, invertElev: 109, maxDepth: 4, depth: 0, isSurcharged: false },
        { id: 'O1', type: 'outfall', x: 750, y: 350, invertElev: 100, maxDepth: 0, depth: 0, isSurcharged: false },
      ],
      links: [
        { id: 'C1', type: 'conduit', fromNode: 'J1', toNode: 'J2', length: 210, roughness: 0.015, flow: 0, capacity: 4 },
        { id: 'C2', type: 'conduit', fromNode: 'J4', toNode: 'J2', length: 250, roughness: 0.015, flow: 0, capacity: 4 },
        { id: 'C3', type: 'conduit', fromNode: 'J2', toNode: 'J3', length: 210, roughness: 0.015, flow: 0, capacity: 5 },
        { id: 'C4', type: 'conduit', fromNode: 'J3', toNode: 'O1', length: 180, roughness: 0.015, flow: 0, capacity: 5 },
      ],
      subcatchments: [],
    },
  },
  {
    id: 'dual-outfall',
    name: 'Dual Outfall System',
    description: 'A network splitting flow between two outfalls — west side drains to a creek, east side to a river. Demonstrates parallel drainage.',
    emoji: '🔱',
    difficulty: 'Advanced',
    nodeCount: 9,
    linkCount: 9,
    model: {
      nodes: [
        { id: 'R1', type: 'raingauge', x: 450, y: 80, invertElev: 0, maxDepth: 0, depth: 0, isSurcharged: false },
        { id: 'J1', type: 'junction', x: 300, y: 180, invertElev: 120, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J2', type: 'junction', x: 600, y: 180, invertElev: 118, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J3', type: 'junction', x: 200, y: 340, invertElev: 112, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J4', type: 'junction', x: 450, y: 300, invertElev: 110, maxDepth: 12, depth: 0, isSurcharged: false },
        { id: 'J5', type: 'junction', x: 700, y: 340, invertElev: 112, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'S1', type: 'storage', x: 450, y: 450, invertElev: 105, maxDepth: 15, depth: 0, isSurcharged: false },
        { id: 'O1', type: 'outfall', x: 100, y: 480, invertElev: 95, maxDepth: 0, depth: 0, isSurcharged: false },
        { id: 'O2', type: 'outfall', x: 800, y: 480, invertElev: 95, maxDepth: 0, depth: 0, isSurcharged: false },
      ],
      links: [
        { id: 'C1', type: 'conduit', fromNode: 'J1', toNode: 'J3', length: 190, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C2', type: 'conduit', fromNode: 'J1', toNode: 'J4', length: 190, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C3', type: 'conduit', fromNode: 'J2', toNode: 'J4', length: 190, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C4', type: 'conduit', fromNode: 'J2', toNode: 'J5', length: 190, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C5', type: 'conduit', fromNode: 'J3', toNode: 'O1', length: 180, roughness: 0.013, flow: 0, capacity: 12 },
        { id: 'C6', type: 'conduit', fromNode: 'J4', toNode: 'S1', length: 150, roughness: 0.013, flow: 0, capacity: 12 },
        { id: 'C7', type: 'conduit', fromNode: 'J5', toNode: 'O2', length: 180, roughness: 0.013, flow: 0, capacity: 12 },
        { id: 'C8', type: 'conduit', fromNode: 'S1', toNode: 'O1', length: 370, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C9', type: 'conduit', fromNode: 'S1', toNode: 'O2', length: 370, roughness: 0.013, flow: 0, capacity: 8 },
      ],
      subcatchments: [],
    },
  },
  {
    id: 'campus-drainage',
    name: 'University Campus',
    description: 'A complex campus drainage system with buildings, parking lots, and green spaces. Multiple storage ponds and rain gauges.',
    emoji: '🎓',
    difficulty: 'Advanced',
    nodeCount: 12,
    linkCount: 13,
    model: {
      nodes: [
        { id: 'R1', type: 'raingauge', x: 250, y: 60, invertElev: 0, maxDepth: 0, depth: 0, isSurcharged: false },
        { id: 'R2', type: 'raingauge', x: 650, y: 60, invertElev: 0, maxDepth: 0, depth: 0, isSurcharged: false },
        { id: 'J1', type: 'junction', x: 150, y: 180, invertElev: 130, maxDepth: 8, depth: 0, isSurcharged: false },
        { id: 'J2', type: 'junction', x: 350, y: 160, invertElev: 128, maxDepth: 8, depth: 0, isSurcharged: false },
        { id: 'J3', type: 'junction', x: 550, y: 180, invertElev: 125, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'J4', type: 'junction', x: 750, y: 160, invertElev: 122, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'S1', type: 'storage', x: 250, y: 340, invertElev: 118, maxDepth: 12, depth: 0, isSurcharged: false },
        { id: 'J5', type: 'junction', x: 450, y: 320, invertElev: 115, maxDepth: 10, depth: 0, isSurcharged: false },
        { id: 'S2', type: 'storage', x: 650, y: 340, invertElev: 112, maxDepth: 14, depth: 0, isSurcharged: false },
        { id: 'J6', type: 'junction', x: 350, y: 470, invertElev: 108, maxDepth: 12, depth: 0, isSurcharged: false },
        { id: 'J7', type: 'junction', x: 550, y: 470, invertElev: 105, maxDepth: 12, depth: 0, isSurcharged: false },
        { id: 'O1', type: 'outfall', x: 450, y: 580, invertElev: 98, maxDepth: 0, depth: 0, isSurcharged: false },
      ],
      links: [
        { id: 'C1', type: 'conduit', fromNode: 'J1', toNode: 'J2', length: 200, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C2', type: 'conduit', fromNode: 'J2', toNode: 'J3', length: 200, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C3', type: 'conduit', fromNode: 'J3', toNode: 'J4', length: 200, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C4', type: 'conduit', fromNode: 'J1', toNode: 'S1', length: 180, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C5', type: 'conduit', fromNode: 'J2', toNode: 'J5', length: 180, roughness: 0.013, flow: 0, capacity: 8 },
        { id: 'C6', type: 'conduit', fromNode: 'J3', toNode: 'J5', length: 170, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C7', type: 'conduit', fromNode: 'J4', toNode: 'S2', length: 200, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C8', type: 'conduit', fromNode: 'S1', toNode: 'J6', length: 160, roughness: 0.013, flow: 0, capacity: 6 },
        { id: 'C9', type: 'conduit', fromNode: 'J5', toNode: 'J6', length: 180, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C10', type: 'conduit', fromNode: 'J5', toNode: 'J7', length: 180, roughness: 0.013, flow: 0, capacity: 10 },
        { id: 'C11', type: 'conduit', fromNode: 'S2', toNode: 'J7', length: 160, roughness: 0.013, flow: 0, capacity: 6 },
        { id: 'C12', type: 'conduit', fromNode: 'J6', toNode: 'O1', length: 150, roughness: 0.013, flow: 0, capacity: 14 },
        { id: 'C13', type: 'conduit', fromNode: 'J7', toNode: 'O1', length: 150, roughness: 0.013, flow: 0, capacity: 14 },
      ],
      subcatchments: [],
    },
  },
];
