import { SWMMState } from './swmm-types';

export function generateInpFile(model: SWMMState, title: string = 'SWMMCRAFT Export'): string {
  const lines: string[] = [];

  lines.push('[TITLE]');
  lines.push(`;;${title}`);
  lines.push(`;;Generated by SWMMCRAFT Ultimate`);
  lines.push('');

  lines.push('[OPTIONS]');
  lines.push('FLOW_UNITS           CFS');
  lines.push('INFILTRATION         HORTON');
  lines.push('FLOW_ROUTING         DYNWAVE');
  lines.push('LINK_OFFSETS         DEPTH');
  lines.push('FORCE_MAIN_EQUATION  H-W');
  lines.push('IGNORE_RAINFALL      NO');
  lines.push('IGNORE_SNOWMELT      YES');
  lines.push('IGNORE_GROUNDWATER   YES');
  lines.push('IGNORE_RDII          YES');
  lines.push('IGNORE_ROUTING       NO');
  lines.push('IGNORE_QUALITY       YES');
  lines.push('ALLOW_PONDING        NO');
  lines.push('SKIP_STEADY_STATE    NO');
  lines.push('START_DATE           01/01/2024');
  lines.push('START_TIME           00:00:00');
  lines.push('REPORT_START_DATE    01/01/2024');
  lines.push('REPORT_START_TIME    00:00:00');
  lines.push('END_DATE             01/02/2024');
  lines.push('END_TIME             00:00:00');
  lines.push('SWEEP_START          01/01');
  lines.push('SWEEP_END            12/31');
  lines.push('DRY_DAYS             0');
  lines.push('REPORT_STEP          00:05:00');
  lines.push('WET_STEP             00:05:00');
  lines.push('DRY_STEP             01:00:00');
  lines.push('ROUTING_STEP         00:00:30');
  lines.push('');

  const raingauges = model.nodes.filter(n => n.type === 'raingauge');
  if (raingauges.length > 0) {
    lines.push('[RAINGAGES]');
    lines.push(';;Name           Format  Interval  SCF  Source');
    lines.push(';;-------------- ------- --------- ---- ----------');
    raingauges.forEach(rg => {
      lines.push(`${rg.id.padEnd(17)}INTENSITY 0:05      1.0  TIMESERIES  DesignStorm`);
    });
    lines.push('');
  }

  const junctions = model.nodes.filter(n => n.type === 'junction');
  if (junctions.length > 0) {
    lines.push('[JUNCTIONS]');
    lines.push(';;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded');
    lines.push(';;-------------- ---------- ---------- ---------- ---------- ----------');
    junctions.forEach(j => {
      lines.push(`${j.id.padEnd(17)}${j.invertElev.toFixed(2).padEnd(11)}${j.maxDepth.toFixed(2).padEnd(11)}0${' '.repeat(10)}0${' '.repeat(10)}0`);
    });
    lines.push('');
  }

  const outfalls = model.nodes.filter(n => n.type === 'outfall');
  if (outfalls.length > 0) {
    lines.push('[OUTFALLS]');
    lines.push(';;Name           Elevation  Type       Stage Data       Gated    Route To');
    lines.push(';;-------------- ---------- ---------- ---------------- -------- ----------------');
    outfalls.forEach(o => {
      lines.push(`${o.id.padEnd(17)}${o.invertElev.toFixed(2).padEnd(11)}FREE${' '.repeat(7)}${' '.repeat(17)}NO`);
    });
    lines.push('');
  }

  const storages = model.nodes.filter(n => n.type === 'storage');
  if (storages.length > 0) {
    lines.push('[STORAGE]');
    lines.push(';;Name           Elev.    MaxDepth   InitDepth  Shape      Curve Name/Params            SurDepth  Fevap    Psi      Ksat     IMD');
    lines.push(';;-------------- -------- ---------- ---------- ---------- ---------------------------- --------- -------- -------- -------- --------');
    storages.forEach(s => {
      lines.push(`${s.id.padEnd(17)}${s.invertElev.toFixed(2).padEnd(9)}${s.maxDepth.toFixed(2).padEnd(11)}0${' '.repeat(10)}FUNCTIONAL 1000      0         0${' '.repeat(10)}0`);
    });
    lines.push('');
  }

  const conduits = model.links.filter(l => l.type === 'conduit');
  if (conduits.length > 0) {
    lines.push('[CONDUITS]');
    lines.push(';;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow');
    lines.push(';;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------');
    conduits.forEach(c => {
      lines.push(`${c.id.padEnd(17)}${c.fromNode.padEnd(17)}${c.toNode.padEnd(17)}${c.length.toFixed(2).padEnd(11)}${c.roughness.toFixed(4).padEnd(11)}0${' '.repeat(10)}0${' '.repeat(10)}0${' '.repeat(10)}0`);
    });
    lines.push('');

    lines.push('[XSECTIONS]');
    lines.push(';;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert');
    lines.push(';;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------');
    conduits.forEach(c => {
      const diam = (c.diameter || 1.5).toFixed(2);
      lines.push(`${c.id.padEnd(17)}CIRCULAR     ${diam.padEnd(17)}0${' '.repeat(10)}0${' '.repeat(10)}0${' '.repeat(10)}1`);
    });
    lines.push('');
  }

  if (model.subcatchments.length > 0) {
    lines.push('[SUBCATCHMENTS]');
    lines.push(';;Name           Rain Gage        Outlet           Area       %Imperv    Width      %Slope     CurbLen    SnowPack');
    lines.push(';;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------');
    model.subcatchments.forEach(s => {
      const rainGage = raingauges.length > 0 ? raingauges[0].id : '*';
      const outlet = s.outletNode || (junctions.length > 0 ? junctions[0].id : '*');
      lines.push(`${s.id.padEnd(17)}${rainGage.padEnd(17)}${outlet.padEnd(17)}${s.area.toFixed(2).padEnd(11)}${s.percentImperv.toFixed(2).padEnd(11)}500${' '.repeat(8)}0.5${' '.repeat(8)}0`);
    });
    lines.push('');

    lines.push('[SUBAREAS]');
    lines.push(';;Subcatchment   N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted');
    lines.push(';;-------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------');
    model.subcatchments.forEach(s => {
      lines.push(`${s.id.padEnd(17)}0.01${' '.repeat(7)}0.1${' '.repeat(8)}0.05${' '.repeat(7)}0.05${' '.repeat(7)}25${' '.repeat(9)}OUTLET`);
    });
    lines.push('');
  }

  lines.push('[COORDINATES]');
  lines.push(';;Node           X-Coord            Y-Coord');
  lines.push(';;-------------- ------------------ ------------------');
  model.nodes.forEach(n => {
    lines.push(`${n.id.padEnd(17)}${n.x.toFixed(3).padEnd(19)}${n.y.toFixed(3)}`);
  });
  lines.push('');

  if (model.subcatchments.some(s => s.points.length > 0)) {
    lines.push('[Polygons]');
    lines.push(';;Subcatchment   X-Coord            Y-Coord');
    lines.push(';;-------------- ------------------ ------------------');
    model.subcatchments.forEach(s => {
      s.points.forEach(p => {
        lines.push(`${s.id.padEnd(17)}${p.x.toFixed(3).padEnd(19)}${p.y.toFixed(3)}`);
      });
    });
    lines.push('');
  }

  lines.push('[REPORT]');
  lines.push('INPUT      YES');
  lines.push('CONTROLS   YES');
  lines.push('SUBCATCHMENTS ALL');
  lines.push('NODES ALL');
  lines.push('LINKS ALL');
  lines.push('');

  return lines.join('\n');
}

export function downloadInpFile(model: SWMMState, filename: string = 'swmmcraft_export.inp') {
  const content = generateInpFile(model, filename.replace('.inp', ''));
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
